// Mock data for ArNet Enterprise SaaS Platform
import type { User, Customer, Conversation, AIAgent, SystemStatus } from '@/types/domain'

export const mockCurrentUser: User = {
  id: 'user-001',
  name: 'Joana',
  email: 'joana@arnet.com.br',
  role: 'manager',
  department: 'Gestora',
  lastActiveAt: new Date(),
  createdAt: new Date('2024-01-15'),
}

export const mockCustomers: Customer[] = [
  {
    id: 'cust-001',
    name: 'TechCorp Brasil',
    email: 'contato@techcorp.com.br',
    phone: '+55 11 99999-0001',
    company: 'TechCorp Brasil LTDA',
    segment: 'enterprise',
    status: 'active',
    healthScore: 85,
    totalRevenue: 450000,
    lastInteractionAt: new Date(),
    createdAt: new Date('2023-06-10'),
  },
  {
    id: 'cust-002',
    name: 'Varejo Express',
    email: 'suporte@varejoexpress.com.br',
    phone: '+55 21 98888-0002',
    company: 'Varejo Express SA',
    segment: 'mid-market',
    status: 'active',
    healthScore: 72,
    totalRevenue: 125000,
    lastInteractionAt: new Date(Date.now() - 86400000),
    createdAt: new Date('2023-09-22'),
  },
  {
    id: 'cust-003',
    name: 'StartupFlow',
    email: 'hello@startupflow.io',
    company: 'StartupFlow Inc',
    segment: 'small-business',
    status: 'prospect',
    healthScore: 60,
    totalRevenue: 0,
    createdAt: new Date('2024-02-01'),
  },
]

export const mockConversations: Conversation[] = [
  {
    id: 'conv-001',
    customerId: 'cust-001',
    customerName: 'TechCorp Brasil',
    channel: 'chat',
    status: 'open',
    priority: 'high',
    assignedAIAgentId: 'ai-001',
    subject: 'Integração API - Dúvidas técnicas',
    lastMessage: 'Preciso de ajuda com a autenticação OAuth2',
    unreadCount: 3,
    sentiment: 'neutral',
    tags: ['api', 'integração', 'técnico'],
    startedAt: new Date(Date.now() - 3600000),
    updatedAt: new Date(),
  },
  {
    id: 'conv-002',
    customerId: 'cust-002',
    customerName: 'Varejo Express',
    channel: 'whatsapp',
    status: 'pending',
    priority: 'medium',
    assignedAgentId: 'user-002',
    subject: 'Problema com faturamento',
    lastMessage: 'A cobrança veio duplicada este mês',
    unreadCount: 1,
    sentiment: 'negative',
    tags: ['faturamento', 'urgente'],
    startedAt: new Date(Date.now() - 7200000),
    updatedAt: new Date(Date.now() - 1800000),
  },
  {
    id: 'conv-003',
    customerId: 'cust-003',
    customerName: 'StartupFlow',
    channel: 'email',
    status: 'open',
    priority: 'low',
    assignedAIAgentId: 'ai-002',
    subject: 'Dúvidas sobre planos',
    lastMessage: 'Qual a diferença entre os planos Pro e Enterprise?',
    unreadCount: 0,
    sentiment: 'positive',
    tags: ['vendas', 'planos'],
    startedAt: new Date(Date.now() - 86400000),
    updatedAt: new Date(Date.now() - 43200000),
  },
]

export const mockAIAgents: AIAgent[] = [
  {
    id: 'ai-001',
    name: 'Atlas',
    type: 'assistant',
    status: 'active',
    model: 'gpt-4-turbo',
    description: 'Assistente principal de atendimento ao cliente',
    capabilities: ['atendimento', 'resolução de problemas', 'escalonamento inteligente'],
    conversationsHandled: 1247,
    avgResponseTime: 1200,
    satisfactionScore: 94,
    lastActiveAt: new Date(),
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'ai-002',
    name: 'Luna',
    type: 'classifier',
    status: 'active',
    model: 'claude-3-opus',
    description: 'Classificador e roteador de conversas',
    capabilities: ['classificação', 'análise de sentimento', 'priorização'],
    conversationsHandled: 3892,
    avgResponseTime: 450,
    satisfactionScore: 91,
    lastActiveAt: new Date(),
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'ai-003',
    name: 'Iris',
    type: 'summarizer',
    status: 'training',
    model: 'gpt-4',
    description: 'Gerador de resumos e relatórios',
    capabilities: ['sumarização', 'extração de insights', 'relatórios'],
    conversationsHandled: 892,
    avgResponseTime: 2100,
    satisfactionScore: 88,
    createdAt: new Date('2024-02-01'),
  },
]

export const mockSystemStatus: SystemStatus = {
  websocket: 'connected',
  aiAgentsActive: 2,
  aiAgentsTotal: 3,
  lastSync: new Date(),
}
